parameters:
    stevotvr.groupsub.currencies:
        AUD: $
        BRL: R$
        CAD: $
        CHF: Fr
        CZK: Kč
        DKK: kr
        EUR: €
        GBP: £
        HKD: $
        HUF: Ft
        ILS: ₪
        JPY: ¥
        MXN: $
        MYR: RM
        NOK: kr
        NZD: $
        PHP: ₱
        PLN: zł
        RUB: ₽
        SEK: kr
        SGD: $
        THB: ฿
        TWD: $
        USD: $
