imports:
    - { resource: tables.yml }
    - { resource: currencies.yml }

services:
    stevotvr.groupsub.cron.task.main:
        class: stevotvr\groupsub\cron\task\main
        arguments:
            - '@config'
            - '@stevotvr.groupsub.operator.subscription'
        calls:
            - method: set_name
              arguments:
                - cron.task.stevotvr.groupsub
        tags:
            - { name: cron.task }
    stevotvr.groupsub.notification.type:
        class: stevotvr\groupsub\notification\type\base_type
        abstract: true
        parent: notification.type.base
        calls:
            - method: setup
              arguments:
                - '@controller.helper'
                - '@user_loader'
    stevotvr.groupsub.notification.type.warn:
        class: stevotvr\groupsub\notification\type\warn
        shared: false
        parent: stevotvr.groupsub.notification.type
        tags:
            - { name: notification.type }
    stevotvr.groupsub.notification.type.expired:
        class: stevotvr\groupsub\notification\type\expired
        shared: false
        parent: stevotvr.groupsub.notification.type
        tags:
            - { name: notification.type }
    stevotvr.groupsub.controller.acp:
        class: stevotvr\groupsub\controller\acp_base_controller
        abstract: true
        arguments:
            - '@config'
            - '@service_container'
            - '@stevotvr.groupsub.operator.currency'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
    stevotvr.groupsub.controller.acp.settings:
        class: stevotvr\groupsub\controller\acp_settings_controller
        parent: stevotvr.groupsub.controller.acp
    stevotvr.groupsub.controller.acp.product:
        class: stevotvr\groupsub\controller\acp_prods_controller
        parent: stevotvr.groupsub.controller.acp
        calls:
            - method: setup
              arguments:
                - '@group_helper'
                - '@stevotvr.groupsub.operator.product'
                - '@stevotvr.groupsub.operator.unit_helper'
    stevotvr.groupsub.controller.acp.subscription:
        class: stevotvr\groupsub\controller\acp_subs_controller
        parent: stevotvr.groupsub.controller.acp
        calls:
            - method: setup
              arguments:
                - '@stevotvr.groupsub.operator.product'
                - '@stevotvr.groupsub.operator.subscription'
                - '@pagination'
                - '@user'
            - method: set_path_info
              arguments:
                - '%core.root_path%'
                - '%core.php_ext%'
    stevotvr.groupsub.controller.ipn:
        class: stevotvr\groupsub\controller\ipn_controller
        arguments:
            - '@config'
            - '@service_container'
            - '@stevotvr.groupsub.operator.currency'
            - '@request'
            - '@stevotvr.groupsub.operator.subscription'
    stevotvr.groupsub.controller.main:
        class: stevotvr\groupsub\controller\main_controller
        arguments:
            - '@config'
            - '@service_container'
            - '@stevotvr.groupsub.operator.currency'
            - '@controller.helper'
            - '@language'
            - '@stevotvr.groupsub.operator.product'
            - '@stevotvr.groupsub.operator.subscription'
            - '@template'
            - '@stevotvr.groupsub.operator.unit_helper'
            - '@user'
    stevotvr.groupsub.entity:
        class: stevotvr\groupsub\entity\entity
        abstract: true
        arguments:
            - '@dbal.conn'
    stevotvr.groupsub.entity.product:
        class: stevotvr\groupsub\entity\product
        parent: stevotvr.groupsub.entity
        shared: false
        arguments:
            - '%stevotvr.groupsub.tables.products%'
        calls:
            - method: setup
              arguments:
                - '@config'
                - '%stevotvr.groupsub.currencies%'
    stevotvr.groupsub.entity.subscription:
        class: stevotvr\groupsub\entity\subscription
        parent: stevotvr.groupsub.entity
        shared: false
        arguments:
            - '%stevotvr.groupsub.tables.subs%'
    stevotvr.groupsub.operator:
        class: stevotvr\groupsub\operator\operator
        abstract: true
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.groupsub.tables.products%'
            - '%stevotvr.groupsub.tables.groups%'
            - '%stevotvr.groupsub.tables.subs%'
    stevotvr.groupsub.operator.product:
        class: stevotvr\groupsub\operator\product
        parent: stevotvr.groupsub.operator
        calls:
            - method: setup
              arguments:
                - '@group_helper'
    stevotvr.groupsub.operator.subscription:
        class: stevotvr\groupsub\operator\subscription
        parent: stevotvr.groupsub.operator
        calls:
            - method: setup
              arguments:
                - '@config'
                - '@notification_manager'
            - method: set_path_info
              arguments:
                - '%core.root_path%'
                - '%core.php_ext%'
    stevotvr.groupsub.operator.unit_helper:
        class: stevotvr\groupsub\operator\unit_helper
        arguments:
            - '@language'
    stevotvr.groupsub.operator.currency:
        class: stevotvr\groupsub\operator\currency
        arguments:
            - '%stevotvr.groupsub.currencies%'
