imports:
    - { resource: tables.yml }

services:
    stevotvr.groupsub.entity.product:
        class: stevotvr\groupsub\entity\product
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%stevotvr.groupsub.tables.products%'
    stevotvr.groupsub.entity.subscription:
        class: stevotvr\groupsub\entity\subscription
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.groupsub.tables.subs%'
    stevotvr.groupsub.operator.product:
        class: stevotvr\groupsub\operator\product
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.groupsub.tables.products%'
            - '%stevotvr.groupsub.tables.groups%'
            - '%stevotvr.groupsub.tables.subs%'
    stevotvr.groupsub.operator.subscription:
        class: stevotvr\groupsub\operator\subscription
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.groupsub.tables.products%'
            - '%stevotvr.groupsub.tables.groups%'
            - '%stevotvr.groupsub.tables.subs%'
