parameters:
    stevotvr.groupsub.tables.packages: '%core.table_prefix%groupsub_packages'
    stevotvr.groupsub.tables.groups: '%core.table_prefix%groupsub_groups'
    stevotvr.groupsub.tables.prices: '%core.table_prefix%groupsub_prices'
    stevotvr.groupsub.tables.subs: '%core.table_prefix%groupsub_subs'
